export const ActionTypes = {
    SET_ROUTES: 'SET_ROUTES',
    GET_TABLE_ROUTES: 'GET_TABLE_ROUTES',
    SET_TABLE_DATA: 'SET_TABLE_DATA',
    SET_TABLE_COLUMNS: 'SET_TABLE_COLUMNS',
    GET_MAP_ROUTE: 'GET_MAP_ROUTE',
    SET_MARKERS: 'SET_MARKERS',
    CLEAR_MARKERS: 'CLEAR_MARKERS',
    GET_WAYPOINTS: 'GET_WAYPOINTS',
    SET_WAYPOINTS: 'SET_WAYPOINTS',
    CLEAR_WAYPOINTS: 'CLEAR_WAYPOINTS',
}
